<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function getProjects()
    {
        $em = $this->getEntityManager();
        $query = $this->createQueryBuilder("p")
            ->where("p.precio > :precio")
            ->setParameter("precio", "79")
            ->getQuery();
        $projects = $query->getResult();

        return $projects;
    }
}
