blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /web

mi:
    resource: "@MiBundle/Resources/config/routing.yml"
    prefix:   /

rutas_bundle:
  resource: "@AppBundle/Resources/config/routing.yml"
  prefix: /
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
