# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app.twig_extension:
    class: AppBundle\Twig\HelperViews
    public: true
    tags:
      - {name: twig.extension}

  app.twig_filter:
      class: AppBundle\Twig\FilterViews
      public: true
      tags:
        - {name: twig.extension}