AppBundle\Entity\Project:
    type: entity
    table: projects
    repositoryClass: AppBundle\Repository\ProjectRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titulo:
            type: string
            length: 255
        descripcion:
            type: string
            length: 255
        precio:
            type: float
    lifecycleCallbacks: {  }
